### ISSUE TITLE
Drag Drop

### ISSUE THREAD

**Issue by deathblade89** [Hoogkamer/vue-org-chart#12]
Hi there,

Lovely demo, looks like you guys are doing a fantastic job here!

Is there any way that you can implement drag drop -> movement of departments or teams hierarchy using drag and drop?

Thanks

**Comment by Hoogkamer** [comment]
Thank you!

I have considered to do that, but when you have a larger chart, you might need to drag the department quite a bit. Also you might need to navigate (search for) a department where you want to move it to. So cut/paste is easiest and suitable for every situation. I tried to simulate drag and drop a bit by showing the department you are moving at the cursor.
