### ISSUE TITLE
Add two parents to chart, not one

### ISSUE THREAD

**Issue by NicaBihovetz** [Hoogkamer/vue-org-chart#18]
Hi! 
Thank you for this amazing instrument! But I have a question for you.
So...If We have 2 parents on top of our chart, how to solve this problem? 
How can I add two parents to the chart top?

**Comment by Hoogkamer** [comment]
Hi,

If you have 2 top parents, I suspect you have 2 different orgcharts. What you could do then is to copy the sources to 2 different folders and create 2 different charts.
Or you can add an 'artificial'  parent to the 2 parents. But I do think there is always one legal entity with a person who is in the end accountable.

This app is programmed in such a way that you have 1 top parent where everything eventually rolls up to. Also each child must have exactly 1 parent. 
You can argue that a child could have multiple parents, for example when you have a 'functional' and 'reporting'  structure in your organization. But this is more complex to build, so not supported (yet?)

**Comment by NicaBihovetz** [comment]
Thanks for your answer! In my situation the whole team is simultaneously subordinate to several equal leaders. 
For example, can you imagine a family tree? A family tree, which information is located from top to bottom: from descendants (children) to ancestors (parents). And one child may have a sibling. Accordingly, the parents of the children are the same.

**Comment by Hoogkamer** [comment]
Ok, I understand. If this happens at many places, you might be better of by a family tree application.

As a quick fix in this application, you could create a "Family"  department, then add the 2 manages as "staff department"  and then add the rest as normal department.

Hope this helps!

![image4526](https://user-images.githubusercontent.com/17671871/79110097-f9949300-7d79-11ea-9b5f-187673125606.png)
