### ISSUE TITLE
Want to add new filed in Person Vue

### ISSUE THREAD

**Issue by Eyffes** [Hoogkamer/vue-org-chart#36]
Hi and thank you for this job.
is there any way to add new field in ShowPerson View?
Thanks

**Comment by Hoogkamer** [comment]
Hi, this is a valid point. Currently it is not possible, I will have a look at it

**Comment by Hoogkamer** [comment]
@Eyffes You can now add your custom fields, see: https://freeorgchart.netlify.app/#faq
