### ISSUE TITLE
field staff_department - Pay attention to the letters ... what do they mean?

### ISSUE THREAD

**Issue by baha96** [Hoogkamer/vue-org-chart#40]
hi, thanks for your hard work, 
could you explain what these letters are in this field(staff_department)?
why structure depends on this field?

**Comment by Hoogkamer** [comment]
Hi, thank you.

If a department is a staff department it will be put to the side(s), and above the other child departments.
In the demo these are 'office' , 'strategy & systainabilitty' and ' communication' 

So the only thing it does is placing it closer to the parent (and above the other children)
