### ISSUE TITLE
Down and Up arrow (doShowChildren toggle) not working on mobile browser

### ISSUE THREAD

**Issue by askynet** [Hoogkamer/vue-org-chart#45]
DeptBox.vue =>doShowChildren toggle is not working mobile browser. Tried both chrome and safari browser.

Steps: 
1. Enable browser responsive view from chrome or safari.
2. Choose any mobile device resolution.
3. Click on down or up arrows, it's not working

Expected : doShowChildren toggle should show and hide the children of the current node.

**Comment by Hoogkamer** [comment]
Hi, 
The issue should be fixed now.
However this application is not optimized for mobile/touchscreen, it is primarily meant as a desktop application.

Regards
