### ISSUE TITLE
Any plan to support mobile UI,can be viewed in mobile device more friendly 

### ISSUE THREAD

**Issue by randyguogithub** [Hoogkamer/vue-org-chart#5]
Any plan to support mobile UI,can be viewed in mobile device more friendly

**Comment by Hoogkamer** [comment]
Currently I have no such plans. But if there are any suggestions how to make it more mobile friendly, I could have a look at this.
So what would a mobile friendly version look like, a big graph is then not possible.

**Comment by randyguogithub** [comment]
yip, that would be an issue for a big graph
