### ISSUE TITLE
Data size limit issue

### ISSUE THREAD

**Issue by Ekingg** [Hoogkamer/vue-org-chart#6]
Is there a limit to the data.js data size? The current Chart data has more than 3,000 lines  (Department), how to make it work.

**Comment by Hoogkamer** [comment]
I have used it for around that amount of departments. There is no limit, except for what the browser can keep. Do you come accross performance problems? What is the error? Which browser?

**Comment by Ekingg** [comment]
The script "985822c6fa697be21ce1.js" used 20.88s to load, Is there any way optimization load speed ?
![image](https://user-images.githubusercontent.com/3412810/56105940-56941800-5f71-11e9-87f4-d7e549379555.png)

**Comment by Hoogkamer** [comment]
What I do now is pre-calculate the complete tree in memory, this costs much time. To solve this, only the visible part of the tree should be calculated. But this will need a relative big refactoring of the code.

**Comment by Hoogkamer** [comment]
@Ekingg Using a quick fix, the loading time should be half the time now

**Comment by Hoogkamer** [comment]
The data is stored as a tree now, greatly improving load performance.
To get the new format, "Generate Inputfile" again, and place data.js in root
