### ISSUE TITLE
Can we add some animation in this chart?

### ISSUE THREAD

**Issue by matinwd** [Hoogkamer/vue-org-chart#62]
Thanks for your great library
Is there any way that we can run some idea like this?
For example i want to add an image on lines of chart running to another rectangle
Is that possible?
Like in the head of chart one image comes down and moves to Finance section (in live demo of your library)

**Comment by Hoogkamer** [comment]
Hi, you probably need some animation library for that, which is not used here (like d3.js). So it is not possible to do it (easily)
