### ISSUE TITLE
Assignment worksheet will not update 

### ISSUE THREAD

**Issue by digitalstimulants** [Hoogkamer/vue-org-chart#69]
If I delete all the content that comes with the stand alone version and try to add my own Departments, people and assignments the assignments do not copy to the exported excel file if they are already in my list of people.  I have to manually add them and that seems to defeat the purpose of the import?  Is there something that I'm missing?  Thanks

**Comment by digitalstimulants** [comment]
> If I delete all the content that comes with the stand alone version and try to add my own Departments, people and assignments the assignments do not copy to the exported excel file if they are already in my list of people. I have to manually add them and that seems to defeat the purpose of the import? Is there something that I'm missing? Thanks

I figured it out... my bad

**Comment by Hoogkamer** [comment]
Great.
