### ISSUE TITLE
SVG lines don't match up to department boxes when boxes are variable height

### ISSUE THREAD

**Issue by dandrewrichardson** [Hoogkamer/vue-org-chart#72]
I came across this in my fork. I needed to have some department boxes that were bigger than others, but this caused problems with drawing the SVG lines to the correct vertical spot. This is solved by changing line 721 in store/index.js to the following

`pos.element.bottom - pos.parent.bottom - pos.element.height / 2`

See the image for what I'm describing when I mean "variable box height." Note that the code change does not seem to cause any issues with the current default code, but I have not tested in isolation.

![screenshot](https://user-images.githubusercontent.com/9815587/176764339-03465d57-108a-4809-b33d-8952af17b8dc.png)

**Comment by Hoogkamer** [comment]
Thank you, I changed it.
Regards, Michael
