### ISSUE TITLE
Count all the headcounts

### ISSUE THREAD

**Issue by hastelloy** [Hoogkamer/vue-org-chart#8]
Current the number of sub-departments was shown. 
Is it possible to show all the headcounts under the manager, not only the direct reports?

**Comment by Hoogkamer** [comment]
Indeed, now there is only a count of the direct children. 

Do you mean sum of all children (departments) underneath? So "Desktop development" will have a count of 6.

Or the number of people in that department? So " IOS" will have a count of 7 (leaving out the manager)

**Comment by hastelloy** [comment]
Sum of all the children underneath would make sense from the prospective of HR. Under "Desktop development" department, there are 7 people (including the mgr)... in another word... Mgr. of "Desktop development" is leading a team of 7 people. You might set an option for showing ___Number of Direct Reports__ or __Number of Team___ or ___both___.

BTW, thanks for this easy and nice tool for creating org chart quickly. It let me break away from the tools like Microsoft Visio.  Sorry I am not familiar with front end and cannot help for the coding...

**Comment by Hoogkamer** [comment]
Thanks, it is also nice to have feedback on how to improve the application.
I will pick this up

**Comment by Hoogkamer** [comment]
Count of people is added to the chart now.

**Comment by hastelloy** [comment]
When number of people in the department is checked, only IOS is shown 7. I am not understanding why. Is that correct?

**Comment by Hoogkamer** [comment]
Yes, there are only people in the IOS department, the rest do not have any. 
(see the people tab in the left sidescreen)
