### ISSUE TITLE
Using HTML in department description

### ISSUE THREAD

**Issue by olegchepjakov** [Hoogkamer/vue-org-chart#84]
Hi!
Is it possible to use HTML tags in department descriptions?
Or use line breaks?
Thanks.

**Comment by Hoogkamer** [comment]
Hi, I added the option to use HTML in the description

**Comment by olegchepjakov** [comment]
> Hi, I added the option to use HTML in the description

Thank you!

**Comment by olegchepjakov** [comment]
I'm sorry. But is it possible to allow html to be used in text fields? For example, in a person's profile, field type = text.
