### ISSUE TITLE
Possibilities 

### ISSUE THREAD

**Issue by y0d4a** [Hoogkamer/vue-org-chart#90]
Hi,

I need a specific org., i think this chart cannot accomplish that.
In structure, there are VP folks and directors, VP is 1st under the CEO and has people under it and there is a second level which is Directors.
Things is that some directors are solo (direct report to the CEO) and some are under the VP (both have teams under it).
So, I need lines to be connected in that way, right now I see that there is only way one under another.

Am I right? Or am I missing something?

Thank you

**Comment by Hoogkamer** [comment]
Hi, yes it is only possible to have one parent for a child department

**Comment by y0d4a** [comment]
Eh :(
Ok, thank you for the help!

**Comment by y0d4a** [comment]
Eh :(
Ok, thank you for the answer!
