### ISSUE TITLE
config for simple parent child

### ISSUE THREAD

**Issue by bradyguyc** [Hoogkamer/vue-org-chart#91]
Is there away to easily configure the org chart with an csv file like the following:

name(unique), manager (name from first field, title, direct count, indirect count, total

and have it build an org chart based off of name and manager and display the title, direct count, indirect count, and total fields in the box?

**Comment by Hoogkamer** [comment]
You can use HTML in the department name, and then hide the name of the manager (and employee count) in the settings for example. As you can see this however makes the html tags also show in the sidebar, which I could probably fix.

![image](https://github.com/Hoogkamer/vue-org-chart/assets/17671871/412baedf-f335-4dd6-8d46-49ebf7e0fd76)
