### ISSUE TITLE
Created a PR with my "data"

### ISSUE THREAD

**Issue by renevanosnabrugge** [Hoogkamer/vue-org-chart#93]
Hi @Hoogkamer . Thanks for your awesome repo. I created a org chart with some names, and filed a PR . per accident to the fork (default option in GH). Can please delete my PR rvo-data? so the data does not show up in the PR history ??
Thanks!

**Comment by Hoogkamer** [comment]
Hi, I don't see any open PR, did you manage to solve it yourself?
