### ISSUE TITLE
Example Maximum call stack exceeded

### ISSUE THREAD

**Issue by delcon** [Hoogkamer/vue-org-chart#94]
Great work!
I cloned your repo and started in dev.
The console then shows maximum call stack exceeded

![image](https://github.com/Hoogkamer/vue-org-chart/assets/9477898/1067e6e5-d67f-45cb-9f5d-eba0e3c31bae)

before that a lot of nuxt errors show also

![image](https://github.com/Hoogkamer/vue-org-chart/assets/9477898/bcfac0b8-1e3f-408c-9efc-3679cc7db151)

**Comment by Hoogkamer** [comment]
Hi, I was not able to upgrade this because the newer Nuxt version needs a webserver to run as far as I know.
Can you try to run it with Node 14?

**Comment by delcon** [comment]
I am useing node v20
Nuxt has a dev-server built in. `npx nuxi@latest init`

**Comment by Hoogkamer** [comment]
I meant, it will not run on a fileserver anymore when I upgrade. That was one of the key benefits of this solution. But can you try to run it with node v14 and see if that works for you?
